version: '3.7'

services:
  dataset-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user1
      POSTGRES_DB: pdf
    ports:
      - 5432:5432

volumes:
  pdf_storage:
