version: '3.7'

services:
  dataset-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user1
      POSTGRES_DB: pdf
    ports:
      - 5432:5432

  rabbit-mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pdf_storage:
