version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: user1
      POSTGRES_DB: pdf

  rabbit-mq:
    image: rabbitmq:3-management

  server:
    image: thealt/pdf_server:latest
    depends_on:
      - postgres
      - rabbit-mq
    volumes:
      - type: volume
        source: pdf_storage
        target: /pdf_storage
    working_dir: /pdf/pdf_server
    command: python main.py
    ports:
      - 5000:5000

  worker:
    image: thealt/pdf_server:latest
    depends_on:
      - server
    restart: on-failure
    volumes:
      - type: volume
        source: pdf_storage
        target: /pdf_storage
    working_dir: /pdf/pdf_worker
    command: dramatiq worker

volumes:
  pdf_storage:
